name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_id: ${{ fromJson(steps.create-release.outputs.result).id }}
      release_upload_url: ${{ fromJson(steps.create-release.outputs.result).upload_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$(node -p "require('./zapcut/package.json').version")" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        id: create-release
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${{ steps.get_version.outputs.VERSION }}`,
              name: `ZapCut v${{ steps.get_version.outputs.VERSION }}`,
              body: 'Release notes for version ${{ steps.get_version.outputs.VERSION }}',
              draft: true,
              prerelease: false
            })
            return {
              id: data.id,
              upload_url: data.upload_url
            }

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
            arch: aarch64
            platform_name: macos-aarch64
            friendly_name: MacBook-AppleSilicon
            ffmpeg_url: https://evermeet.cx/ffmpeg/getrelease/ffmpeg/zip
            ffprobe_url: https://evermeet.cx/ffmpeg/getrelease/ffprobe/zip
            
          - platform: macos-latest
            target: x86_64-apple-darwin
            arch: x86_64
            platform_name: macos-x86_64
            friendly_name: MacBook-Intel
            ffmpeg_url: https://evermeet.cx/ffmpeg/getrelease/ffmpeg/zip
            ffprobe_url: https://evermeet.cx/ffmpeg/getrelease/ffprobe/zip
            
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            arch: amd64
            platform_name: linux-x86_64
            friendly_name: Linux
            ffmpeg_url: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
            
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x64
            platform_name: windows-x86_64
            friendly_name: Windows
            ffmpeg_url: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip

    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: zapcut/package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install frontend dependencies
        working-directory: zapcut
        run: npm ci

      - name: Download FFmpeg for macOS
        if: startsWith(matrix.platform, 'macos')
        working-directory: zapcut/src-tauri
        run: |
          echo "Downloading FFmpeg for ${{ matrix.platform_name }}"
          mkdir -p binaries/${{ matrix.platform_name }}
          cd binaries/${{ matrix.platform_name }}
          
          # Download and extract ffmpeg
          curl -L ${{ matrix.ffmpeg_url }} -o ffmpeg.zip
          unzip -o ffmpeg.zip
          chmod +x ffmpeg
          rm ffmpeg.zip
          
          # Download and extract ffprobe
          curl -L ${{ matrix.ffprobe_url }} -o ffprobe.zip
          unzip -o ffprobe.zip
          chmod +x ffprobe
          rm ffprobe.zip
          
          # Verify
          ./ffmpeg -version
          ./ffprobe -version

      - name: Download FFmpeg for Linux
        if: matrix.platform == 'ubuntu-22.04'
        working-directory: zapcut/src-tauri
        run: |
          echo "Downloading FFmpeg for ${{ matrix.platform_name }}"
          mkdir -p binaries/${{ matrix.platform_name }}
          cd binaries/${{ matrix.platform_name }}
          
          # Download and extract
          wget -q ${{ matrix.ffmpeg_url }}
          tar -xf ffmpeg-release-amd64-static.tar.xz
          mv ffmpeg-*-amd64-static/ffmpeg .
          mv ffmpeg-*-amd64-static/ffprobe .
          chmod +x ffmpeg ffprobe
          rm -rf ffmpeg-*-amd64-static*
          
          # Verify
          ./ffmpeg -version
          ./ffprobe -version

      - name: Download FFmpeg for Windows
        if: matrix.platform == 'windows-latest'
        working-directory: zapcut/src-tauri
        shell: pwsh
        run: |
          Write-Host "Downloading FFmpeg for ${{ matrix.platform_name }}"
          New-Item -ItemType Directory -Force -Path "binaries/${{ matrix.platform_name }}"
          Set-Location "binaries/${{ matrix.platform_name }}"
          
          # Download and extract
          Invoke-WebRequest -Uri "${{ matrix.ffmpeg_url }}" -OutFile "ffmpeg.zip"
          Expand-Archive -Path "ffmpeg.zip" -DestinationPath "." -Force
          
          # Find and move binaries
          $ffmpegDir = Get-ChildItem -Directory -Filter "ffmpeg-*" | Select-Object -First 1
          Move-Item -Path "$($ffmpegDir.FullName)/bin/ffmpeg.exe" -Destination "." -Force
          Move-Item -Path "$($ffmpegDir.FullName)/bin/ffprobe.exe" -Destination "." -Force
          
          # Cleanup
          Remove-Item -Recurse -Force $ffmpegDir
          Remove-Item -Force "ffmpeg.zip"
          
          # Verify
          ./ffmpeg.exe -version
          ./ffprobe.exe -version

      - name: Update Tauri config with platform-specific resources
        working-directory: zapcut/src-tauri
        run: |
          echo "Updating tauri.conf.json for platform: ${{ matrix.platform_name }}"
          python3 update_tauri_config.py --platform ${{ matrix.platform_name }}

      - name: Build frontend
        working-directory: zapcut
        run: npm run build

      - name: Build Tauri app
        working-directory: zapcut
        run: npm run tauri build -- --target ${{ matrix.target }}

      - name: Rename artifacts (macOS)
        if: startsWith(matrix.platform, 'macos')
        working-directory: zapcut/src-tauri/target/${{ matrix.target }}/release/bundle
        run: |
          # Find the DMG and rename it
          DMG_FILE=$(find dmg -name "*.dmg" | head -n 1)
          if [ -n "$DMG_FILE" ]; then
            VERSION=$(node -p "require('../../../../../package.json').version")
            NEW_NAME="ZapCut_${VERSION}_${{ matrix.friendly_name }}.dmg"
            cp "$DMG_FILE" "$NEW_NAME"
            echo "Renamed: $DMG_FILE -> $NEW_NAME"
            echo "DMG_PATH=$(pwd)/$NEW_NAME" >> $GITHUB_ENV
          fi
          
          # Find the .app.tar.gz and rename it
          APP_TAR=$(find macos -name "*.app.tar.gz" | head -n 1)
          if [ -n "$APP_TAR" ]; then
            VERSION=$(node -p "require('../../../../../package.json').version")
            NEW_APP_NAME="ZapCut_${VERSION}_${{ matrix.friendly_name }}.app.tar.gz"
            cp "$APP_TAR" "$NEW_APP_NAME"
            echo "Renamed: $APP_TAR -> $NEW_APP_NAME"
            echo "APP_TAR_PATH=$(pwd)/$NEW_APP_NAME" >> $GITHUB_ENV
          fi

      - name: Rename artifacts (Windows)
        if: matrix.platform == 'windows-latest'
        working-directory: zapcut/src-tauri/target/${{ matrix.target }}/release/bundle
        shell: pwsh
        run: |
          # Find the MSI and rename it
          $msiFile = Get-ChildItem -Path "msi" -Filter "*.msi" -Recurse | Select-Object -First 1
          if ($msiFile) {
            $version = (Get-Content "../../../../../package.json" | ConvertFrom-Json).version
            $newName = "ZapCut_${version}_${{ matrix.friendly_name }}.msi"
            Copy-Item $msiFile.FullName -Destination $newName
            Write-Host "Renamed: $($msiFile.Name) -> $newName"
            echo "MSI_PATH=$(Get-Location)\$newName" >> $env:GITHUB_ENV
          }
          
          # Find the NSIS installer and rename it
          $nsisFile = Get-ChildItem -Path "nsis" -Filter "*-setup.exe" -Recurse | Select-Object -First 1
          if ($nsisFile) {
            $version = (Get-Content "../../../../../package.json" | ConvertFrom-Json).version
            $newName = "ZapCut_${version}_${{ matrix.friendly_name }}-setup.exe"
            Copy-Item $nsisFile.FullName -Destination $newName
            Write-Host "Renamed: $($nsisFile.Name) -> $newName"
            echo "NSIS_PATH=$(Get-Location)\$newName" >> $env:GITHUB_ENV
          }

      - name: Rename artifacts (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        working-directory: zapcut/src-tauri/target/${{ matrix.target }}/release/bundle
        run: |
          # Find the DEB and rename it
          DEB_FILE=$(find deb -name "*.deb" | head -n 1)
          if [ -n "$DEB_FILE" ]; then
            VERSION=$(node -p "require('../../../../../package.json').version")
            NEW_NAME="zapcut_${VERSION}_${{ matrix.friendly_name }}.deb"
            cp "$DEB_FILE" "$NEW_NAME"
            echo "Renamed: $DEB_FILE -> $NEW_NAME"
            echo "DEB_PATH=$(pwd)/$NEW_NAME" >> $GITHUB_ENV
          fi
          
          # Find the AppImage and rename it
          APPIMAGE_FILE=$(find appimage -name "*.AppImage" | head -n 1)
          if [ -n "$APPIMAGE_FILE" ]; then
            VERSION=$(node -p "require('../../../../../package.json').version")
            NEW_NAME="zapcut_${VERSION}_${{ matrix.friendly_name }}.AppImage"
            cp "$APPIMAGE_FILE" "$NEW_NAME"
            echo "Renamed: $APPIMAGE_FILE -> $NEW_NAME"
            echo "APPIMAGE_PATH=$(pwd)/$NEW_NAME" >> $GITHUB_ENV
          fi

      - name: Upload DMG to release (macOS)
        if: startsWith(matrix.platform, 'macos') && env.DMG_PATH != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ${{ env.DMG_PATH }}
          asset_name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && format('ZapCut_{0}_{1}.dmg', steps.get_version.outputs.VERSION, matrix.friendly_name) || format('ZapCut_{0}_{1}.dmg', 'dev', matrix.friendly_name) }}
          asset_content_type: application/x-apple-diskimage

      - name: Upload APP.TAR.GZ to release (macOS)
        if: startsWith(matrix.platform, 'macos') && env.APP_TAR_PATH != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ${{ env.APP_TAR_PATH }}
          asset_name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && format('ZapCut_{0}_{1}.app.tar.gz', steps.get_version.outputs.VERSION, matrix.friendly_name) || format('ZapCut_{0}_{1}.app.tar.gz', 'dev', matrix.friendly_name) }}
          asset_content_type: application/gzip

      - name: Upload MSI to release (Windows)
        if: matrix.platform == 'windows-latest' && env.MSI_PATH != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ${{ env.MSI_PATH }}
          asset_name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && format('ZapCut_{0}_{1}.msi', steps.get_version.outputs.VERSION, matrix.friendly_name) || format('ZapCut_{0}_{1}.msi', 'dev', matrix.friendly_name) }}
          asset_content_type: application/x-msi

      - name: Upload NSIS installer to release (Windows)
        if: matrix.platform == 'windows-latest' && env.NSIS_PATH != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ${{ env.NSIS_PATH }}
          asset_name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && format('ZapCut_{0}_{1}-setup.exe', steps.get_version.outputs.VERSION, matrix.friendly_name) || format('ZapCut_{0}_{1}-setup.exe', 'dev', matrix.friendly_name) }}
          asset_content_type: application/x-msdownload

      - name: Upload DEB to release (Linux)
        if: matrix.platform == 'ubuntu-22.04' && env.DEB_PATH != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ${{ env.DEB_PATH }}
          asset_name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && format('zapcut_{0}_{1}.deb', steps.get_version.outputs.VERSION, matrix.friendly_name) || format('zapcut_{0}_{1}.deb', 'dev', matrix.friendly_name) }}
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload AppImage to release (Linux)
        if: matrix.platform == 'ubuntu-22.04' && env.APPIMAGE_PATH != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ${{ env.APPIMAGE_PATH }}
          asset_name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && format('zapcut_{0}_{1}.AppImage', steps.get_version.outputs.VERSION, matrix.friendly_name) || format('zapcut_{0}_{1}.AppImage', 'dev', matrix.friendly_name) }}
          asset_content_type: application/x-executable
